import Footer from "../../components/footer/footer";
import Header from "../../components/header/header";
import "./globals.css";
import { Questrial } from "next/font/google";

const questrial = Questrial({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={questrial.className}>
        <Header />
        {children} 
        <Footer />
      </body>
    </html>
  );
}
