import './globals.css'
import { Questrial } from 'next/font/google'

const questrial = Questrial({  weight: '400',
subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={questrial.className}>{children}</body>
    </html>
  )
}
